#!/bin/bash


puppetsme=~/puppets.me
puppetsrep=~/puppets


case "$1" in
	"-install")
		echo $2 > $puppetsme 
		echo "installed"
		;;
	"-update")
		;;
	*)		
		echo "usage pup-check {-install <deviceName> | -update }" 
		done;;
esac
echo "updating" 
me=`cat $puppetsme`

svn co http://proj.googlecode.com/svn/trunk/puppets $puppetsrep

for pp in $(find $puppetsrep/$me/ -name *.pp;find $puppetsrep/all/ -name *.pp);
do
        echo
        echo '*******************************'
        echo $pp
        echo '*******************************'
        echo

        puppet apply $pp
done
echo OK!


