#!/bin/sh

# wget https://proj.googlecode.com/svn/trunk/puppets/register0 && chmod 700 ./register0 && ./register0 && rm ./register0

echo OK!
sudo su
cd ~
apt-get update
apt-get install subversion
apt-get install puppet
svn co http://proj.googlecode.com/svn/trunk/puppets ~/puppets
chmod 700 ./puppets/register
./puppets/register pi

