#!/bin/bash


puppetsme=~/puppets.me
puppetsrep=~/puppets
me=$1

if [[ '$me' == '' ]];
then
  me=`cat $puppetsme` ;
else
  echo $me > $puppetsme ;
fi

svn co http://proj.googlecode.com/svn/trunk/puppets $puppetsrep

for pp in $(ls $puppetsrep/$me/*.pp; ls $puppetsrep/all/*.pp);
do
        echo
        echo '*******************************'
        echo $pp
        echo '*******************************'
        echo

        puppet apply $pp
done
echo OK!


